global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'aurea-orchestrator'
    static_configs:
      - targets: ['aurea-orchestrator:5000']
    metrics_path: '/metrics'
