apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurea-orchestrator
  namespace: aurea-orchestrator
  labels:
    app.kubernetes.io/name: aurea-orchestrator
    app.kubernetes.io/part-of: aurea-orchestrator
